# NOTE: These are the poses of the waypoints that are drawn on map.png

waypoints:
  - id_1:
      x: 0.92
      y: 2.39
      theta: 1.5708
      neighbours:
        - id_2
        - id_11
        - id_13
        - id_15
  - id_2:
      x: -0.28
      y: 4.25
      theta: 1.5708
      neighbours:
        - id_1
        - id_4
        - id_6
        - id_9
  - id_4: # arm_0
      x: -0.885
      y: 3.48
      theta: 1.5708
      neighbours:
        - id_2
  - id_6: 
      x: 0.58
      y: 5.31
      theta: 0.0
      neighbours:
        - id_2
        - id_7
  - id_7: # arm_1
      x: -0.18
      y: 5.81
      theta: 0.0
      neighbours:
        - id_6
  - id_8:
      x: -2.27
      y: 3.08
      theta: 0.0
      neighbours:
        - id_9
        - id_14
  - id_9:
      x: -0.96
      y: 4.59
      theta: -1.5708
      neighbours:
        - id_2
        - id_8
  - id_10:
      x: 2.97
      y: 1.61
      theta: 3.14159
      neighbours:
        - id_11
        - id_12
  - id_11:
      x: 1.97
      y: 2.49
      theta: 3.14159
      neighbours:
        - id_1
        - id_10
        - id_13
  - id_12:
      x: 2.17
      y: 0.67
      theta: 3.14159
      neighbours:
        - id_10
        - id_13
  - id_13:
      x: 1.14
      y: 1.56
      theta: 3.14159
      neighbours:
        - id_1
        - id_11
        - id_12
        - id_15
  - id_14:
      x: -1.13
      y: 2.28
      theta: 0.0
      neighbours:
        - id_8
        - id_15
  - id_15:
      x: -0.04
      y: 1.25
      theta: 0.0
      neighbours:
        - id_13
        - id_14